function out = compute_combined(image)
    im2 = rgb2gray(im2double(image));
    im = rgb2gray(image);
    
    %image = rgb2ycbcr(image);
    image = rgb2hsv(image);
    %image = rgb2lab(image);
    %im3 = im2double(image(:,:,3));
    out = [
          %compute_a(im2, 2), compute_ghist(im2) % trova illuminazione
          %compute_glcm(im2) % trova l'ombra
          %compute_average_color(image)
          %compute_CEDD(image), ...
          %compute_lbp(im2), ...
          compute_stdev(image(:,:,2)), ...
          compute_a(image(:,:,2), 1)
          %extractHOGFeatures(im2)
    ];

%     compute_glcm(im), ...
%     compute_a(image, 1), ...
%     compute_a(image, 2), ...
%     compute_a(image, 3) ...
%     compute_average_color(image), ...
%     compute_stdev(image), ...
%     compute_lbp(image), ...
%     compute_CEDD(image)
end